name: manga_easy_recommendations
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  
  manga_easy_themes:
    git:
      url: https://github.com/lucascardo12/manga_easy_themes.git
      ref: 1.0.0
  manga_easy_sdk:
    git:
      url: https://github.com/lucascardo12/manga_easy_sdk

  coffee_cup:
    git:
      url: https://github.com/lucascardo12/manga_easy_coffee_cup
  like_button: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

